name: Checks
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn typecheck